spring:
    application:
        name: demo
    profiles:
        active: @env@
    jackson:
        serialization.write_dates_as_timestamps: false
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
