spring:
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://myDb:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: false
